### ISSUE TITLE
Add Useful resources for CP-DSA

### ISSUE THREAD

**Issue by Vishruth-S** [TLE-MEC/Hack-CP#17]
Add useful resources related to Competitive Programming and DSA.
Some examples include Articles related to CP/DS & Algo, tips for cracking ACM ICPC/Code Jam etc, Cheatsheets, tips for cracking coding interviews and many more.
If you have got any such links to some resources which you feel would be really useful, you may add them to 
[CP-DSA_RESOURCES.md](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CP-DSA_RESOURCES.md) 😃

**Comment by Zaid23** [comment]
Hey @Vishruth-S, I Would like to add some, can you assign it to me ?

**Comment by prahuljose** [comment]
hey @Vishruth-S I can add a few problems solutions to the `hackerrank` folder :)

**Comment by Vishruth-S** [comment]
This issue is to open to all

**Comment by sumitmohite0501** [comment]
Hi I would like to add Top 100 problems from Codechef of Div B , C .

**Comment by souvikrajsingh** [comment]
> This issue is to open to all

how do we contribute to it?

**Comment by hannasalam** [comment]
@souvikrajsingh add the resources to [CP-DSA_RESOURCES.md](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CP-DSA_RESOURCES.md) and create a pull request.

**Comment by UKS28** [comment]
@Vishruth-S Can I add some folders of Array ,String ,Bitwise related algorithm ?

**Comment by jainss** [comment]
I also want to add new problem of interview Bit

**Comment by CSAURABH** [comment]
@Vishruth-S I want to add new problem on interview Bit

**Comment by Vishruth-S** [comment]
@jainss  @CSAURABH You can add new problems on InterviewBit. Please refer the contributing guidelines before sending a Pull Request, Thanks
